### ISSUE TITLE
String vs IO based API

### ISSUE THREAD

**Issue by bcardiff** [phenopolis/pluto#12]
Hi, I was intrigued by the memory consumption mentioned in https://blog.phenopolis.com/posts/our-journey-into-crystal-and-image-processing/ and made a quick look in the source code.

I see that read/write of each format requires the whole image data to be in memory more than once.

Example: 

In https://github.com/phenopolis/pluto/blob/078f476a30f6ca167a9c3e0ec5b0af813622a2be/src/pluto/format/ppm.cr#L4 the whole image data is in string and also decoded in the arrays for each rgb.

In https://github.com/phenopolis/thumbnailer/blob/f84979ea448a43d5c531856665a5ab91db6fcbc8/src/thumbnailer.cr#L64 we see that this force consumers to read the whole file in memory.

It should be possible to change the api to:

- `def self.from_ppm(io : IO) : Image`
- `File.open(file_path) { |f| Pluto::Image.from_jpeg(f) }`

This way, the whole file does not need to be read in memory. The current from_ppm implementation even uses IO::Memory.

Similarly, for `def to_ppm : String` it is possible to `def to_ppm(io : IO)` so that consumers can pass a file handler directly.

I'm certain this will decrease the memory consumption.

**Comment by sanks64** [comment]
Thanks for the awesome suggestion! Definitely worth exploring.

I'm not sure when I'll have enough time for this, but if anyone wants to go ahead and do it sooner, I will be happy to review a PR.

**Comment by sanks64** [comment]
@bcardiff Once again thanks for the awesome suggestion.

@Vici37 implemented this. Does it look like what you were thinking about?

I'll be closing this as completed if there are no additional suggestions.

**Comment by bcardiff** [comment]
I see some improvements but Strings are being used to read files fully. Feel free to close and I'll try to send some patches to be more precise when times allows it.

In general using `Slice(UInt8)` (which is aliased as `Bytes`), or if possible directly `IO`, is more idiomatic to express a blob than `String`. 

When doing `String.new(io)` that last `io` will be read fully and it's content duplicated in memory for storing it in the new allocated `String`. 

Depending on the need of libjpeg-turbo you might always need to have the full image in memory, if that's the case there is not a lot of gain between IO and Slice. IO allows a stream based approach which are good for big files, you can consume it in chunks, but if you need the whole thing in memory there is not much to do. 

In general it leads to better results to have a IO based api and build on top of it the String one. The current `Pluto::Format::JPEG` is the other way around, the String is the low level one and when passed a IO a String is built to call the former one.

I also notice there is no call to `tjDestroy` which could be problematic for benchmark and long running processes.

**Comment by sanks64** [comment]
Let's leave this open then.

> I also notice there is no call to `tjDestroy` which could be problematic for benchmark and long running processes.

You mean this? Or something else? https://github.com/phenopolis/pluto/blob/d92dab659962093ebc984f70f72f6bd11b608ab8/src/pluto/format/jpeg.cr#L30

**Comment by sanks64** [comment]
Btw, if you make a better API, feel free to leave it as the only option.

**Comment by bcardiff** [comment]
> You mean this? Or something else? 

Oops, yes 🙈 exactly that one.
