### ISSUE TITLE
Arithmetic overflow with vertical and horizontal blurs with attached image

### ISSUE THREAD

**Issue by Vici37** [phenopolis/pluto#28]
I was experimenting with some other images and came across one that fails in the vertical_blur and horizontal_blur. Through testing, it looks like the operation `(c_value * multiplier).to_u8` is throwing it, where `c_value` ends up as `-1`, causing a negative number trying to be cast `to_u8`. I tried adding a `.clamp(0, 255)`, but it hit the benchmark pretty hard. Making this issue to capture the problem in the meantime.

![moon](https://user-images.githubusercontent.com/1459505/222333646-08546df5-71ff-4b4f-94c6-b29bcd705dc2.jpg)

**Comment by sanks64** [comment]
Could you please see if returning rounding fixes the problem? https://github.com/phenopolis/pluto/pull/8/commits/fa4292fb7453c8edc399e26e12465e4d14f9cc63

**Comment by sanks64** [comment]
If it does, I think adding it back in a PR is the way to go.

**Comment by Vici37** [comment]
It fixes the problem, but with about the same performance hit. Benchmarks that I've recorded:
|                            | Orig | Round | Clamp |
| -------------------------- | ---- | ----- | ----- |
| bilinear_resize!(640, 480) | 16ms | 17ms  | 16ms  |
|           brightness!(1.4) | 3ms  | 3ms   | 3ms   |
|              box_blur!(10) | 8ms  | 13ms  | 13ms  |
| channel_swap!(:red, :blue) | 0ms  | 0ms   | 0ms   |
|             contrast!(128) | 3ms  | 3ms   | 3ms   |
|         gaussian_blur!(10) | 26ms | 40ms  | 39ms  |
|       horizontal_blur!(10) | 3ms  | 6ms   | 6ms   |
|         vertical_blur!(10) | 5ms  | 7ms   | 7ms   |

Memory remains unchanged, so omitting its column. Correctness takes precedence over performance, but there might be a bit twiddle way to do it too.

**Comment by sanks64** [comment]
Given how much work went into [the original implementation](https://blog.ivank.net/fastest-gaussian-blur.html), I'd say it's safe to assume that it's impossible (or difficult) to do otherwise.

**Comment by sanks64** [comment]
I would suggest implementing [this](https://github.com/bfraboni/FastGaussianBlur) and comparing the result if better performance is desired.
